name = "0xkai/nft_marketplace"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project '0xkai/nft_marketplace'"

[repository]
user = "0xkai"
project = "nft_marketplace"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
